image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'cd xastre-market-app/'
    command: "export GITPOD_REPO_ROOT=$PWD && apachectl start 
    && cp .env.example .env 
    && sed -ri -e 's!DB_HOST=db!DB_HOST=localhost!g' .env
    && sed -ri -e 's!DB_PASSWORD=secret!DB_PASSWORD=!g' .env
    && mysql -e 'CREATE DATABASE db_market;'
    && composer install
    && php artisan key:generate
    && php artisan migrate"
