FROM php:8.0.0-apache

ENV TZ=America/Sao_Paulo
ENV COMPOSER_HOME=/tmp/.composer


RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"


RUN apt update \
    && apt install -y libzip-dev zip unzip\
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-configure bcmath --enable-bcmath \
    && docker-php-ext-install -j$(nproc) bcmath \
    && docker-php-ext-configure zip \
    && docker-php-ext-install -j$(nproc) zip \
    && echo "xdebug.mode = debug" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    #&& echo "xdebug.start_with_request = yes" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port = 9003" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log=/tmp/xdebug.log" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.discover_client_host = true" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && a2enmod rewrite \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
&& php -r '$checksum = file_get_contents("https://composer.github.io/installer.sig"); \
if (hash_file("sha384", "composer-setup.php") === $checksum) { echo "Installer verified"; } else { echo "Installer corrupt"; unlink("composer-setup.php"); } echo PHP_EOL;' \
&& php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
&& php -r "unlink('composer-setup.php');"
